### PR TITLE
Introduce Makefile for easy setup

### PR DESCRIPTION
**Pull request by doomspork**
How to test this PR (please do):

```shell
git clone --branch mix-task-setup-content https://github.com/elixirschool/school_house.git test-setup
cd test-setup
make setup
```

### CODE REVIEW

**Review by gemantzu — APPROVED** [review]
:100:

**Review by kinson — APPROVED** [review]
nice & clean 🧼

**Comment by doomspork** [comment]
@kinson would you be interested in joining the org?

**Comment by kinson** [comment]
@doomspork for sure! Thanks!

**Comment by doomspork** [comment]
Sent 🚀

**Pull request merged**
