### PR TITLE
Upgrade to Phoenix 1.6.0-rc.0

### PR DESCRIPTION
**Pull request by kinson**
# Overview

This pr updates does 2 things:
* updates the version of Phoenix from 1.5.9 to 1.6.0-rc.0 and makes the corresponding file changes to support it
* removes ecto-related dependencies and boilerplate since we are not using it for this project

This pr is ~very much a WIP - the remaining items~ ready to go!:
- [x] make sure this branch can deploy to Heroku smoothly
- [x] update *live* templates to use the new `heex` hotness 🔥 
- [x] remove remaining webpack/js related configuratoin
- [x] fix dialyzer error
- [x] fix console error message casued by `Alpine.start()`
- [x] fix `topbar` dependency integration

### References

Of course I could not have done this without Chris & Jose's guidance ❤️ in these two guides:
* https://gist.github.com/chrismccord/2ab350f154235ad4a4d0f4de6decba7b
* https://github.com/josevalim/phx_esbuild_demo/pull/3

### CODE REVIEW

**Comment by doomspork** [comment]
@kinson are we ready to convert this into a PR?

**Comment by kinson** [comment]
> @kinson are we ready to convert this into a PR?

This pr is ready, I am not sure if this is possible, but do you mind redeploying it on Heroku so we can take a look before merging and do some manual testing there?

Two other notes about this pr:
* I am not sure if we want to merge a pre released version of Phoenix, though I haven't heard of any significant regressions or bugs
* In a separate pr I will convert the remaining templates to `heex` - I can do it here instead but it would balloon the size of this pr siginificantly and `eex`/`leex` templates are still supported in 1.6

**Comment by doomspork** [comment]
@kinson sounds good! I will let you know when I deploy this (may be a little bit).

**Comment by kinson** [comment]
Since [Phoenix 1.6.0](https://github.com/phoenixframework/phoenix/releases/tag/v1.6.0) has been officially released, I will upgrade to it before this pr gets merged 🎊

**Pull request closed without merging**
