### PR TITLE
Continue migration from Jekyll to Phoenix 

### LINKED ISSUE #6: Add locale selector to UI
We need to provide a way for user's to select a different locale from the header.

### PR DESCRIPTION
**Pull request by doomspork**
I will expand on this description once the PR is at a stopping point.

Closes #6 #7

### CODE REVIEW

**Comment by gemantzu** [comment]
Looks fine so far :)

**Comment by doomspork** [comment]
Outstanding things I want to address in separate PRs:

1. Displaying pagination for blog posts
2. A page at `/posts/tag/:tag` to show all posts of a given tag

Something else to think about is how we can bubble up older but still relevant blog posts? Maybe under recent on the home page we have some "oldies but goodies"?

**Comment by doomspork** [comment]
The more I think about it the more I think maybe importing the images is less than ideal.

**Comment by gemantzu** [comment]
No it is not...

**Comment by doomspork** [comment]
Do you have any suggestions? The issue is that images need to be in _this_ asset folder to work.

If we don’t import them then this project will forever require a more involved setup to get lessons and posts linked up and then separately to map assets.

**Comment by gemantzu** [comment]
Why? what's wrong with the previous approach? They are not loaded when you have a url of the image?

**Comment by doomspork** [comment]
I’m not sure I follow. The few lessons and blogs that involve images need the image to be served. If the image isn’t in Phoenix how is it going to have URL?

**Comment by gemantzu** [comment]
The same way we did it before? by uploading it "somewhere" and adding the url in the markdown?

**Pull request merged**
