### PR TITLE
Add pagination to blog posts page

### PR DESCRIPTION
**Pull request by cristineguadelupe**
This PR solves #148

This should be seen as a temporary solution. I think it’s worth the price fix the access to the older posts as soon as possible even with a not so elegant solution.
I will work on a more complete solution that allows readers to choose items per page, with pagination working with tags too, an improved and responsive design and a more organized code.

### CODE REVIEW

**Comment by doomspork** [comment]
@cristineguadelupe could you rebase on master to eliminate the conflicts?

**Comment by cristineguadelupe** [comment]
> @cristineguadelupe could you rebase on master to eliminate the conflicts?

Done!

**Comment by kinson** [comment]
@cristineguadelupe I'll pull this down and check it out this evening!

**Review by kinson — APPROVED** [review]
Looks good! Thanks for the fix 🚀

**Pull request merged**
