### PR TITLE
Adds Dark Mode

### PR DESCRIPTION
**Pull request by kinson**
## Scope
This pr updates the website to have a dark/light mode toggle (#56), leveraging tailwind css' dark mode functionality. I also bumped the versions of `phoenix`, `phoenix_html`, and `phoenix_ecto` because the current version was not compatible with elixir v1.12/OTP 24.

### Video

https://user-images.githubusercontent.com/1526888/119243833-9aca4d00-bb27-11eb-9424-bb28ba6867c0.mp4

### CODE REVIEW

**Comment by doomspork** [comment]
This is awesome @kinson! I'll pull this down to check things out but it looks good to me 🎉

**Comment by kinson** [comment]
Thanks @doomspork let me know if any of the colors need to be adjusted

**Review by doomspork — APPROVED** [review]
This is so awesome! Thank you for taking this on!! 💜

**Comment by kinson** [comment]
> @kinson what is your Twitter handle?

It is [`@_kinson_`](https://twitter.com/_kinson_) - and glad to help! Thanks for the guidance :)

**Pull request merged**
