### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by AshutoshSajan**
Add mix phx.server script to start the server

### CODE REVIEW

**Comment by jaimeiniesta** [comment]
@AshutoshSajan I know the rebase thing sounds scary (but it's not!). Maybe for such a small change you can start another PR from the current master branch?

**Comment by AshutoshSajan** [comment]
> @AshutoshSajan I know the rebase thing sounds scary (but it's not that complicated!). Maybe for such a small change, you can start another PR from the current master branch?

ok, yes I guess that would be better

**Comment by AshutoshSajan** [comment]
@jaimeiniesta what is the best way to start an issue?

**Comment by jaimeiniesta** [comment]
To report a new issue you mean? Here:

https://github.com/elixirschool/school_house/issues/new

**Comment by AshutoshSajan** [comment]
> To report a new issue you mean? Here:
> 
> https://github.com/elixirschool/school_house/issues/new

no, I mean how to start working on it, like first, we should create a branch out of master and then make changes there or directly we can make changes on master and create a PR?

**Comment by jaimeiniesta** [comment]
The best way is to create a separate branch for each issue.

**Pull request closed without merging**
