### PR TITLE
Translation report

### PR DESCRIPTION
**Pull request by doomspork**
@gemantzu I know you've been busy so I got started on this. Let me know what you think. You can take over the branch if you want or I can implement the feedback. 

Peek 2021-04-21 16-46

### CODE REVIEW

**Comment by doomspork** [comment]
Need better styling of the section headers. Also want to see about translating those with gettext.

**Comment by doomspork** [comment]
Peek 2021-04-21 18-01

**Comment by gemantzu** [comment]
damn that's perfect! 🔥 🔥 🔥

**Comment by doomspork** [comment]
Any changes you'd like to see @gemantzu or should we move forward with this for now?

**Pull request merged**
