### PR TITLE
replace nprogress with topbar

### PR DESCRIPTION
**Pull request by jaimeiniesta**
nprogress was used in the initial versions of LiveView, but it's 6 years old and has some accessibility issues regarding invalid aria roles, as caught in https://rocketvalidator.com/s/624562a6-bdbe-4411-9c28-3652a4887982/v/15063573

In recent versions of LiveView, topbar is used instead:

http://buunguyen.github.io/topbar/

This PR replaces nprogress with topbar

### CODE REVIEW

**Comment by doomspork** [comment]
Ah ha! I noticed this change in a recent project I generated but I hadn't had time to dig in to see _why_ there was a change.

**Review by doomspork — COMMENTED** [review]
Do we want to remove the package-lock or keep that? I've heard a case for both.

**Comment by jaimeiniesta** [comment]
@doomspork I tend to keep package-lock

**Review by doomspork — APPROVED** [review]
@jaimeiniesta ah ha! The GH UI was showing it as those the file was deleted. I see it was just heavily changed.

**Comment by jaimeiniesta** [comment]
Ah yes, maybe it's because my code editor (VS Code) formatted it? I think I opened the file to see the changes and then it applied formatting.

**Pull request merged**
