### PR TITLE
Lesson Checkpoint Feature: Display Last Read Point on Homepage

### PR DESCRIPTION
**Pull request by yxshv**
I've implemented a new feature in a file called `pickup.js` that saves the last point in the lessons that a user has read. This feature is designed to enhance the user experience by allowing them to easily pick up where they left off in their learning journey.

It saves the pathname and the scrolled value of the last visited lesson and continues at that point 

# Changes Made
- Added a function in pickup.js to store the last read lesson point in local storage.
- Modified the homepage to display a message that guides users to continue their lessons from the last read point.

# Motivation
I found it difficult to remember where I left off in a series of lessons. So I thought I should contribute

---
Here is a gif demonstrating how it works

### CODE REVIEW

**Comment by yxshv** [comment]
anyone?

**Comment by yxshv** [comment]
I really need this feature 😭

**Comment by yxshv** [comment]
two weekends gone :( still waiting

**Review by doomspork — APPROVED** [review]

**Comment by yxshv** [comment]
There is a problem in phone that was unnoticed by me
image

**Pull request merged**
